# Generated by Django 3.1.4 on 2020-12-17 12:15

import bio3.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(storage=bio3.storage_backends.MediaStorage(), upload_to='projects/'),
        ),
    ]
